I'm sorry, but errors were detected in your script. Please correct the
errors listed below, and try again.


The label _call_convoAdv is defined twice, at
  File "game/host.rpy", line 30 and
  File "game/host.rpy", line 83.

Ren'Py Version: Ren'Py 7.3.5.606
Sat Apr 11 12:50:57 2020
